# frozen_string_literal: true
require 'schema_dot_org/schema'
require 'schema_dot_org/schema_type'
require 'schema_dot_org/thing'
require 'schema_dot_org/search_action'
require 'schema_dot_org/web_site'
require 'schema_dot_org/organization'
require 'schema_dot_org/item_list'
require 'schema_dot_org/list_item'
require 'schema_dot_org/person'
require 'schema_dot_org/place'
require 'schema_dot_org/breadcrumb_list'
require 'schema_dot_org/local_business'
require 'schema_dot_org/aggregate_offer'
require 'schema_dot_org/rating'
require 'schema_dot_org/aggregate_rating'
require 'schema_dot_org/creative_work'
require 'schema_dot_org/structured_value'
require 'schema_dot_org/property_value'
require 'schema_dot_org/review'
require 'schema_dot_org/offer'
require 'schema_dot_org/web_page'
require 'schema_dot_org/search_results_page'
require 'schema_dot_org/product'
require 'schema_dot_org/product_model'

module SchemaDotOrg
end
